#!/bin/sh

# Check clang format output
exec git clang-format --diff | grep "^diff" && echo "Clang format failed!" && git clang-format --diff && exit 1

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached HEAD --
